### GET todos
GET http://localhost:3000/api/todos

### POST todo mới
POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "id": 123456,
  "text": "POST",
  "completed": false,
  "createdAt": "2025-04-06T12:00:00Z"
}

### DELETE todo
PUT http://localhost:3000/api/todos
Content-Type: application/json

{
  "id": 123445456,
  "text": "PUT",
  "completed": false,
  "createdAt": "2025-04-06T12:00:00Z"
}