import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Todos",
  description: "Generated by Mingtaing",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-100 transition">
        {children}
      </body>
    </html>
  );
}
